# Generated by Django 4.2.9 on 2026-01-27 01:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import templates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=templates.models.template_upload_path)),
                ('page_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('signature', 'Signature'), ('date', 'Date'), ('checkbox', 'Checkbox')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('recipient', models.CharField(default='Recipient 1', help_text="Recipient identifier (e.g., 'Recipient 1', 'Recipient 2')", max_length=100)),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('x_pct', models.FloatField(help_text='X position as percentage of page width', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('y_pct', models.FloatField(help_text='Y position as percentage of page height', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('width_pct', models.FloatField(help_text='Width as percentage of page width', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('height_pct', models.FloatField(help_text='Height as percentage of page height', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templates.template')),
            ],
            options={
                'ordering': ['page_number', 'y_pct', 'x_pct'],
            },
        ),
    ]
