# Generated by Django 6.0.1 on 2026-02-02 08:52

import django.core.validators
import django.db.models.deletion
import templates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(upload_to=templates.models.template_upload_path),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("signature", "Signature"),
                            ("date", "Date"),
                            ("checkbox", "Checkbox"),
                        ],
                        help_text="Type of input field",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for the field", max_length=255
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        default="Recipient 1",
                        help_text="Recipient identifier (e.g., 'Recipient 1', 'HR Manager')",
                        max_length=100,
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        help_text="Page number (1-indexed)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "x_pct",
                    models.FloatField(
                        help_text="X position as percentage of page width (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "y_pct",
                    models.FloatField(
                        help_text="Y position as percentage of page height (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "width_pct",
                    models.FloatField(
                        help_text="Width as percentage of page width (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "height_pct",
                    models.FloatField(
                        help_text="Height as percentage of page height (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True, help_text="Whether this field must be filled"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="templates.template",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number", "y_pct", "x_pct"],
                "indexes": [
                    models.Index(
                        fields=["template", "page_number"],
                        name="template_page_fields_idx",
                    ),
                    models.Index(
                        fields=["template", "recipient"],
                        name="template_recipient_fields_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("recipient__exact", ""), _negated=True),
                            models.Q(("recipient__isnull", True), _negated=True),
                        ),
                        name="template_field_recipient_required",
                        violation_error_message="Field must be assigned to a recipient",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("width_pct__gt", 0), ("height_pct__gt", 0)),
                        name="template_field_dimensions_positive",
                        violation_error_message="Field width and height must be positive",
                    ),
                ],
            },
        ),
    ]
