# Generated by Django 4.2.9 on 2026-01-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefield",
            name="recipient",
            field=models.CharField(
                default="Recipient 1",
                help_text="Recipient identifier (e.g., 'Recipient 1', 'Recipient 2')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="page_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
