# Generated by Django 4.2.9 on 2026-01-14 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0002_templatefield_recipient_alter_template_page_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="page_count",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
