# Generated by Django 4.2.9 on 2026-02-05 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_add_prefilled_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefield",
            name="height_pct",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="is_editable_prefill",
            field=models.BooleanField(
                default=False,
                help_text="If True, prefilled text can be edited by recipient. If False, text is static/read-only.",
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="page_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="prefill_value",
            field=models.TextField(
                blank=True,
                help_text="Pre-filled text content for prefilled_text field type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="recipient",
            field=models.CharField(
                blank=True,
                help_text="Recipient identifier. Optional for static prefilled fields.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="width_pct",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="x_pct",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="y_pct",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
