# Generated by Django 4.2.9 on 2026-02-03 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_alter_template_page_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefield",
            name="page_number",
            field=models.PositiveIntegerField(
                help_text="Page number (1-indexed)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="recipient",
            field=models.CharField(
                default="Recipient 1",
                help_text="Recipient identifier who must interact with this field",
                max_length=100,
            ),
        ),
    ]
