# Generated by Django 4.2.9 on 2026-02-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("view", "View Only"), ("sign", "Sign")], max_length=10
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Recipient identifier for sign tokens (null for view tokens)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("used", models.BooleanField(default=False)),
                ("revoked", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignatureEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        default="Recipient 1",
                        help_text="Recipient identifier who signed",
                        max_length=100,
                    ),
                ),
                ("signer_name", models.CharField(max_length=255)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "document_sha256",
                    models.CharField(
                        help_text="SHA256 hash of PDF at sign time", max_length=64
                    ),
                ),
                (
                    "event_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash of this signature event for tamper detection",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "field_values",
                    models.JSONField(
                        help_text="Array of {field_id, value} objects signed in this event"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="documents.document",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signature_events",
                        to="signing.signingtoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="signingtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked", False), ("scope", "sign"), ("used", False)
                ),
                fields=("document", "recipient", "scope"),
                name="unique_active_sign_token_per_recipient",
            ),
        ),
    ]
