# Generated by Django 4.2.9 on 2026-02-04 03:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(upload_to=documents.models.document_upload_path),
                ),
                (
                    "signed_file",
                    models.FileField(
                        blank=True,
                        help_text="Flattened PDF with all signatures and overlays merged",
                        null=True,
                        upload_to=documents.models.document_upload_path,
                    ),
                ),
                (
                    "signed_pdf_sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash of the flattened/signed PDF file",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("locked", "Locked for signing"),
                            ("partially_signed", "Partially signed"),
                            ("completed", "Fully signed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("signature", "Signature"),
                            ("date", "Date"),
                            ("checkbox", "Checkbox"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "recipient",
                    models.CharField(help_text="Recipient identifier", max_length=100),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "x_pct",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "y_pct",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "width_pct",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "height_pct",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Field is locked after signing and cannot be edited",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number", "y_pct", "x_pct"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "created_at"], name="documents_d_status_64808e_idx"
            ),
        ),
    ]
