# Generated by Django 6.0.1 on 2026-01-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentfield",
            name="documents_df_page_number_idx",
        ),
        migrations.RemoveIndex(
            model_name="signingtoken",
            name="unique_active_sign_token_per_recipient",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="documents_d_status_64808e_idx",
            old_name="documents_d_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="webhook",
            new_name="documents_w_is_acti_c14ef1_idx",
            old_name="documents_w_is_acti_created_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdeliverylog",
            new_name="documents_w_event_i_f3fe5d_idx",
            old_name="documents_wd_event_created_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="documents_w_webhook_dddf72_idx",
            old_name="documents_we_webhook_status_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="documents_w_event_t_030a07_idx",
            old_name="documents_we_event_t_created_idx",
        ),
        migrations.AddConstraint(
            model_name="signingtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked", False), ("scope", "sign"), ("used", False)
                ),
                fields=("document", "recipient", "scope"),
                name="unique_active_sign_token_per_recipient",
            ),
        ),
    ]
