# Generated by Django 4.2.9 on 2026-01-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="created_from_template",
        ),
        migrations.RemoveField(
            model_name="signingtoken",
            name="single_use",
        ),
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="documentfield",
            name="recipient",
            field=models.CharField(
                default="Recipient 1",
                help_text="Recipient identifier who must fill this field",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="signatureevent",
            name="recipient",
            field=models.CharField(
                default="Recipient 1",
                help_text="Recipient identifier who signed",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="signingtoken",
            name="recipient",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Recipient identifier for sign tokens (null for view tokens)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Field is locked after signing and cannot be edited",
            ),
        ),
        migrations.AddConstraint(
            model_name="signingtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked", False), ("scope", "sign"), ("used", False)
                ),
                fields=("version", "recipient", "scope"),
                name="unique_active_sign_token_per_recipient",
            ),
        ),
    ]
