# Generated by Django 4.2.9 on 2026-02-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentfield",
            index=models.Index(
                fields=["document", "recipient"], name="documents_d_documen_7d920a_idx"
            ),
        ),
    ]
