# Generated by Django 4.2.9 on 2026-02-05 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documentfield_documents_d_documen_7d920a_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfield",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Input"),
                    ("signature", "Signature"),
                    ("date", "Date"),
                    ("checkbox", "Checkbox"),
                    ("initials", "Initials"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="height_pct",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="page_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="recipient",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="width_pct",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="x_pct",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="y_pct",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
