# Generated by Django 4.2.9 on 2026-01-14 07:13

import django.core.validators
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_document_created_from_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentversion",
            name="file",
            field=models.FileField(
                upload_to=documents.models.document_version_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="page_count",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("locked", "Locked for signing"),
                    ("signed", "Fully signed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
