# Generated by Django 4.2.9 on 2026-02-03 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0002_remove_documentfield_documents_df_page_number_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfield",
            name="height_pct",
            field=models.FloatField(
                help_text="Height as percentage of page height",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="page_number",
            field=models.PositiveIntegerField(
                help_text="Page number (1-indexed)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="recipient",
            field=models.CharField(
                default="Recipient 1",
                help_text="Recipient identifier who must interact with this field",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="width_pct",
            field=models.FloatField(
                help_text="Width as percentage of page width",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="x_pct",
            field=models.FloatField(
                help_text="X position as percentage of page width",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="y_pct",
            field=models.FloatField(
                help_text="Y position as percentage of page height",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("document.signature_created", "Signature Created"),
                    ("document.completed", "Document Completed"),
                    ("document.locked", "Document Locked"),
                    ("document.status_changed", "Status Changed"),
                    ("document.test", "Test Event"),
                ],
                help_text="Type of event (e.g., 'document.completed')",
                max_length=50,
            ),
        ),
    ]
