# Generated by Django 4.2.9 on 2026-01-16 09:57

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_documentversion_file_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="signed_file",
            field=models.FileField(
                blank=True,
                help_text="Flattened PDF with all signatures and overlays merged",
                null=True,
                upload_to=documents.models.document_version_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("locked", "Locked for signing"),
                    ("completed", "Fully signed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
