# Generated by Django 4.2.9 on 2026-01-16 10:00

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0004_alter_documentversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureevent',
            name='event_hash',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                help_text='SHA256 hash of this signature event for tamper detection'
            ),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='signed_pdf_sha256',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                help_text='SHA256 hash of the flattened/signed PDF file'
            ),
        ),
    ]