# Generated by Django 4.2.9 on 2026-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_add_prefilled_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfield",
            name="is_editable_prefill",
            field=models.BooleanField(
                default=False,
                help_text="If True, prefilled text can be edited by recipient. If False, text is static/read-only.",
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="prefill_value",
            field=models.TextField(
                blank=True,
                help_text="Pre-filled text content for prefilled_text field type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="recipient",
            field=models.CharField(
                blank=True,
                help_text="Recipient identifier. Optional for static prefilled fields.",
                max_length=255,
                null=True,
            ),
        ),
    ]
