# Generated by Django 4.2.9 on 2026-02-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
