# Generated by Django 4.2.9 on 2026-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_webhookevent_delivery_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="secret",
            field=models.CharField(
                blank=True,
                help_text="Secret key for HMAC-SHA256 signature verification. Keep this private!",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="webhookdeliverylog",
            name="duration_ms",
            field=models.PositiveIntegerField(
                blank=True, help_text="HTTP request duration in milliseconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="payload",
            field=models.JSONField(help_text="Event data sent to webhook (immutable)"),
        ),
    ]
